config/routes.rb
Rails.application.routes.draw do
  get "products/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :articles

  resources :users, only: [ :show ]

  resources :people
  resources :welcome

  resources :products
  # root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  layout "articles"
  # GET /articles or /articles.json
  def index
    @articles = Article.all
    # render "index"
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_path, status: :see_other, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.expect(article: [ :title, :body ])
    end
end

app/controllers/people_controller.rb
require "ostruct"

class PeopleController < ApplicationController
  def show
    @person = OpenStruct.new(name: "David Heinemeier Hansson", bio: "A product of Danish Design during the Winter of '79...")

    respond_to do |format|
      format.xml
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
      @products = Product.all
      # @reviews = Review.where(product_id: @product.id)
      @product_reviews = Review.all.group_by(&:product_id)
    # end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if params[:redirect]
        puts "Redirect flag is set!"
      end
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.expect(product: [ :name, :price, :description ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.json { render :show }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @name = "Himanshi"
    @people = [ "Alice", "Bob", "Charlie" ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

</div>

app/views/articles/_box.html.erb
<div class="box">
  <%= yield if local_assigns[:article] %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_special_layout.html.erb
<div class="article-container">
  <h3>Article #<%= article_counter + 1 %></h3>
  <%= yield %>
  <hr>
</div>

app/views/articles/edit.html.erb
<% content_for :title, "Editing article" %>

<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Articles" %>

<h1>Articles</h1>

<div id="articles">
  <%# <% @articles.each do |article| %>
    <%# <%= render partial: "article", locals: { article: article } %> 
    <%# <p>
      <%= link_to "Show this article", article %>
    <%# </p>
  <% end %> 
  <%= render partial: "article", collection: @articles, layout: "special_layout" %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<% content_for :title, "New article" %>

<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%# <%= render @article %> 
<%= render partial: 'article', layout: 'box', locals: { article: @article } 
# <%# <%= render(layout: 'box') do %>
    <%# <div>
#     <h2><%= @article.title %></h2>
    <%# <p><%= @article.body %></p>
  <%# </div>
<% end %> 

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path

  <%= button_to "Destroy this article", @article, method: :delete, data: { confirm: "Are you sure?" } %>
</div> 

app/views/layouts/_ad_banner.html.erb
<div class="ad-banner">
  <p>🚀 Buy now and get 10% off!</p>
</div>

app/views/layouts/_box.html.erb
<div class="box">
  <h3>Article Details</h3>
  <%= yield if local_assigns[:article] %>
  <hr>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; 2025 My Store</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Action View Overview" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  
  <body>

    <header>
      <h1>Welcome to My Rails App</h1>
    </header>
    
    <nav>
      <%= link_to "Home", root_path %> |
      <%= link_to "Articles", articles_path %>
    </nav>
    <%= yield %>

    <footer>
      <p>&copy; <%= Date.current.year %> My Rails App</p>
    </footer>

  </body>
</html>

app/views/layouts/articles.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articles Layout</title>
</head>
<body>
  <h2>Articles Page</h2>
  <%= yield %>
</body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, placeholder: "Product Name" %>

  <% if local_assigns[:redirect] %>
    <%= form.hidden_field :redirect, value: true %>
  <% end %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%# <div class="product">
  <h2><%= product.name - $<%= product.price %></h2>
  <%# <p><%= product.description %></p>
<%# </div>   %> 

<%# tag.div id: dom_id(my_product) , class: "product" do >
  <h2><%= my_product.name - $<%= my_product.price %></h2>
  <%# <p><%= my_product.description %></p>

 <%# <% if my_reviews.present? %>
    <%# <% my_reviews.each do |review| %>
      <%# <p><%= review.content %></p>
    <%# <% end %>
  <%# <% else %>
    <%# <p>No reviews yet.</p>
  <% end %>
<%# <% end %> 

<%# <p>Product Name: <%= product.name %></p>

<%# <% if local_assigns[:product_reviews] %>
  <%# <p>Reviews: <%= product_reviews.count %></p>
  <%# <ul>
    <% product_reviews.each do |review| %>
      <%# <li><%= review.content %></li>
    <%# <% end %>
  <%# </ul>
<% else %>
  <%# <p>No reviews available.</p>
<% end %>

<%# <div>
  <h3><%= product.name %></h3>
  <%# <p>Price: $<%= product.price %></p>
<%# </div> %> 

<%# <div class="product">
  <p><strong>Product <%= product_counter + 1 : </strong> <%= product.name %></p>
  <%# <p><strong>Price:</strong> $<%= product.price %></p>
<%# </div>  %>


<% local_assigns => { product:, **options } %>

<%= tag.div id: dom_id(product), **options do %>
  <h1><%= product.name %></h1>
<% end %>

<div class="product">
  <p><strong>Product <%= product_counter + 1 %>:</strong> <%= product.name %></p>
  <p><strong>Price:</strong> $<%= product.price %></p>
</div>

app/views/products/_product_ruler.html.erb
<hr class="product-ruler">

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<%= render "layouts/ad_banner" %>

<h1>Products</h1>
<%# 
<% @products.each do |product| %> 
  <%# <%= render partial: "product", locals: { my_product: product, my_reviews: @reviews[product.id] || []  } %>
  <%# <%= render partial: "product", locals: { product: product, product_reviews: @product_reviews[product.id] || []} %>
   <%# <%= render partial: "product", locals: { product: product } %> 

   <%= render partial: @products, spacer_template: "product_ruler" %>
<%# <% end %> 

<%= render "layouts/footer" %>

  

app/views/products/new.html.erb
<% content_for :title, "New product" %>

<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%# <%= render @product %> 

<%# <%= render partial: "product", locals: { my_product: @product, my_reviews: @reviews } %> 

<%# <%= render partial: "product", locals: { product: @product } %>

<%# <%= render partial: "product", locals: { product: @product, product_reviews: @product.reviews } %>

<%# <%= render partial: "form", locals: { product: @product, redirect: true } %> 

<%= render partial: "product", collection: @products %>




<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome, <%= @name %>!</h1>

<ul>
  <% @people.each do |person| %>
    <li><%= person %></li>
  <% end %>
</ul>